services:
  - name: appgamonaltrasporti-back
    type: web
    runtime: node
    plan: free
    buildCommand: npm install -g pnpm@10.27.0 && pnpm install --frozen-lockfile && npx prisma generate && PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK=1 npx prisma migrate deploy
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: RESET_TOKEN_EXPIRES_MINUTES
        value: 30
      - key: R2_SIGNED_URL_EXPIRES_SECONDS
        value: 900
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESET_PASSWORD_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
